FROM node:18-alpine AS builder

WORKDIR /usr/src/app

RUN npm i -g pnpm

COPY package*.json ./

RUN pnpm install

COPY . .

FROM node:18-alpine AS runner

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /usr/src/app

RUN npm i -g pnpm

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package.json ./package.json
COPY --from=builder /usr/src/app/next.config.mjs ./next.config.mjs
COPY --from=builder /usr/src/app/src ./src
COPY --from=builder /usr/src/app .

EXPOSE 4000

USER appuser

CMD ["pnpm", "dev"]
